"""empty message

Revision ID: 53ccf0acca37
Revises: 
Create Date: 2025-02-26 10:40:09.530099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ccf0acca37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('ponds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('soil_testing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dose_rate', sa.String(length=200), nullable=True))

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('soil_testing', schema=None) as batch_op:
        batch_op.drop_column('dose_rate')

    with op.batch_alter_table('ponds', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('monitoring_log', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
